[supervisord]
user=root
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

# [program:hls_monitor]
# command=/bin/bash /home/diode/hls.sh
# directory=/home/diode
# autostart=true
# autorestart=true
# user=diode
# stdout_logfile=/home/diode/log/hls.log
# stderr_logfile=/home/diode/log/hls.err

[program:vnc_monitor]
command=/bin/bash /home/diode/vnc.sh
directory=/home/diode
autostart=true
autorestart=true
user=diode
stdout_logfile=/home/diode/log/vnc.log
stderr_logfile=/home/diode/log/vnc.err

[program:diode_dest]
command= python3 /home/diode/diode_dest/diode_dest.py
directory=/home/diode/
autostart=true
autorestart=true
user=diode
stdout_logfile=/log/diode_dest.log
stderr_logfile=/log/diode_dest.log

[program:cron]
command= /usr/sbin/cron -f
directory=/
autostart=true
autorestart=true
user=root

[program:weapon_server]
command=/bin/bash /home/weapon_server/chal/start_server.sh
directory=/home/weapon_server/chal/
umask=002
autostart=true
autorestart=true
user=weapon_server
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile=/log/weapon_server.log
stdout_logfile=/log/weapon_server.log


[program:weapon_auth]
command=/bin/bash /home/weapon_authent/chal/start_auth.sh
directory=/home/weapon_authent/chal/
autostart=true
autorestart=true
user=weapon_authent
depends=weapon_server
stderr_logfile=/log/weapon_supervisor.log
stdout_logfile=/log/weapon_supervisor.log
