[supervisord]
user=root
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sftp]
command=/sbin/sshd -D  -f /root/sftp/sshd_config
directory=/home/diode
autostart=true
autorestart=true
user=root
stdout_logfile=/root/sftp.log
stderr_logfile=/root/sftp.err


[program:diode_src]
command=/home/diode/diode_src
directory=/sftp/
autostart=true
autorestart=true
user=diode
stdout_logfile=/home/diode/diode.log
stderr_logfile=/home/diode/diode.log

